---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: alertmanager-config-controller
    kubernetes.io/cluster-service: "true"
  name: alertmanager-config-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager-config-controller
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: alertmanager-config-controller
    spec:
      containers:
      - args:
         - --selector=type=alertmanager
         - kube-system
         - alertmanager-config
        image: quay.io/bakins/alertmanager-config-controller:0.1.1
        name: controller
      - name: kubectl
        image: gcr.io/google_containers/hyperkube:v1.5.2
        command:
          - /kubectl
          - proxy
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
