apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-receiver-email
  labels:
    type: alertmanager
  annotations:
    alertmanager-type: Receiver
data:
  spec: |-
    name: 'team-X-mails'
    email_configs:
     - to: 'team-X+alerts@example.org'
